---
  - name: install tools
    apt: name=python-mysqldb state=present 

  - name: install mysql
    apt: 
      name: mysql-server
      state: present


  - name: ensure listen on all interfaces
    lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
    notify: restart database
    
  - name: enable mysql
    service: name=mysql state=started enabled=yes

  - name: create demo database
    mysql_db: name=demo state=present

  - name: create mysql user
    mysql_user: name={{ db_username }} password={{ db_password }}} priv={{ db_name }}.*:ALL host='{{ db_host }}' state=present