---
  - hosts: database
    become: true
    tasks:
      - name: install tools
        apt: name=python-mysqldb state=present update_cache=yes

      - name: install mysql
        apt: 
          name: mysql-server
          state: present
          update_cache: yes

      - name: enable mysql
        service: name=mysql state=started enabled=yes

      - name: ensure listen on all interfaces
        lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = {{ ansible_eth0.ipv4.address }}"
        notify: restart database
      
      - name: create demo database
        mysql_db: name=demo state=present

      - name: create mysql user
        mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

    handlers:
      - name: restart database
        service: name=mysql state=restarted


