---
  - hosts: loadbalancer
    gather_facts: false
    become: true
    tasks:
      - name: verify nginx service
        command: service nginx status
        changed_when: false

      - name: verify port 80
        wait_for: port=80 timeout=3

  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: verify apache service
        command: service apache2 status
        changed_when: false

      - name: verify port 80
        wait_for: port=80 timeout=3

  - hosts: database
    become: true
    tasks:
      - name: verify mysql service
        command: service mysql status
        changed_when: false

      - name: verify port 3306
        wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=3

  - hosts: bastion
    gather_facts: false
    tasks: 
      - name: verify loadbalancer response
        uri: url=http://{{item}} return_content=yes
        with_items: "{{ groups.loadbalancer }}"
        register: lb_index

      - name: debug index
        debug: var=lb_index

      - fail:
          msg: index failed to return content
        when: "'Hello, from sunny' not in item.content"
        with_items: "{{lb_index.results}}"

  - hosts: loadbalancer
    gather_facts: false
    tasks: 
      - name: verify web response
        uri: url=http://{{item}} return_content=yes
        register: web_index
        with_items: "{{ groups.webserver }}"

      - fail: 
          msg: index failed to return content
        when: "'Hello, from sunny {{item.item}}!' not in item.content"
        with_items: "{{ web_index.results }}"

