---
  - hosts: loadbalancer
    gather_facts: false
    tasks:
      - name: stop nginx
        service: name=nginx state=stopped 
      - wait_for: port=80 state=drained

  - hosts: webserver
    gather_facts: false
    tasks:
      - name: stop apache
        service: name=apache2 state=stopped 
      - wait_for: port=80 state=stopped        

  - hosts: database
    become: true
    gather_facts: false
    tasks:
      - name: restart mysql
        service: name=mysql state=restarted
      - wait_for: port=3306

  - hosts: webserver
    gather_facts: false
    tasks:
      - name: start apache
        service: name=apache2 state=started
      - wait_for: port=80

  - hosts: loadbalancer
    gather_facts: false
    tasks:
      - name: start nginx
        service: name=nginx state=started 
      - wait_for: port=3306